CREATE TABLE IF NOT EXISTS `worldtimezone_setting` (
	`idx` int(11) NOT NULL auto_increment,
	`seq` int(10) NOT NULL,
	`pws_timezone` varchar(200) NOT NULL,
	`pws_format` int(2) NOT NULL,
	PRIMARY KEY (idx)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
				

CREATE TABLE IF NOT EXISTS `worldtimezone_timezone` (
	`pwt_idx` int(11) NOT NULL auto_increment,
	`pwt_gmt` varchar(5) NOT NULL,
	`pwt_country` varchar(100) NOT NULL,
	`pwt_state` varchar(100) NOT NULL,
	`pwt_city` varchar(200) NOT NULL,
	`pwt_location` varchar(200) NOT NULL,
	`pwt_continent` varchar(100) NOT NULL,
	PRIMARY KEY (pwt_idx)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
				

INSERT INTO `worldtimezone_timezone` (`pwt_gmt`, `pwt_country`, `pwt_state`, `pwt_city`, `pwt_location`, `pwt_continent`) VALUES

		('+0000','Republic of Cote d\'Ivoire','','Abidjan','Africa/Abidjan','Africa'),
		('+0000','Ghana','','Accra','Africa/Accra','Africa'),
		('+0300','Eritrea','','Asmara','Africa/Asmara','Africa'),
		('+0300','Eritrea','','Asmera','Africa/Asmera','Africa'),
		('+0000','Mali','','Bamako','Africa/Bamako','Africa'),
		('+0100','Central African Republic','','Bangui','Africa/Bangui','Africa'),
		('+0000','Gambia','','Banjul','Africa/Banjul','Africa'),
		('+0000','Guinea Bissau','','Bissau','Africa/Bissau','Africa'),
		('+0200','Malawi','','Blantyre','Africa/Blantyre','Africa'),
		('+0100','Congo','','Brazzaville','Africa/Brazzaville','Africa'),
		('+0200','Burundi','','Bujumbura','Africa/Bujumbura','Africa'),
		('+0300','Egypt','','Cairo','Africa/Cairo','Africa'),
		('+0000','Morocco','','Casablanca','Africa/Casablanca','Africa'),
		('+0200','Spain','','Ceuta','Africa/Ceuta','Africa'),
		('+0000','Guinea','','Conakry','Africa/Conakry','Africa'),
		('+0000','Senegal','','Dakar','Africa/Dakar','Africa'),
		('+0300','Tanzania','','Dar es Salaam ','Africa/Dar_es_Salaam','Africa'),
		('+0300','Djibouti','','Djibouti City','Africa/Djibouti','Africa'),
		('+0100','Cameroon','','Douala','Africa/Douala','Africa'),
		('+0000','Western Sahara','','El Aaiun','Africa/El_Aaiun','Africa'),
		('+0000','Sierra Leone','','Freetown','Africa/Freetown','Africa'),
		('+0200','Botswana','','Gaborone','Africa/Gaborone','Africa'),
		('+0200','Zimbabwe','','Harare','Africa/Harare','Africa'),
		('+0200','South Africa','','Johannesburg','Africa/Johannesburg','Africa'),
		('+0300','Uganda','','Kampala','Africa/Kampala','Africa'),
		('+0300','Sudan','','Khartoum','Africa/Khartoum','Africa'),
		('+0200','Rwanda','','Kigali','Africa/Kigali','Africa'),
		('+0100','Congo','','Kinshasa','Africa/Kinshasa','Africa'),
		('+0100','Nigeria','','Lagos','Africa/Lagos','Africa'),
		('+0100','Gabon','','Libreville','Africa/Libreville','Africa'),
		('+0000','Togo','','Lome','Africa/Lome','Africa'),
		('+0100','Angola','','Luanda','Africa/Luanda','Africa'),
		('+0200','Congo','','Lubumbashi','Africa/Lubumbashi','Africa'),
		('+0200','Zambia','','Lusaka','Africa/Lusaka','Africa'),
		('+0100','Equatorial Guinea','','Malabo','Africa/Malabo','Africa'),
		('+0200','Mozambique','','Maputo','Africa/Maputo','Africa'),
		('+0200','Lesotho','','Maseru','Africa/Maseru','Africa'),
		('+0200','Swaziland','','Mbabane','Africa/Mbabane','Africa'),
		('+0300','Somalia','','Mogadishu','Africa/Mogadishu','Africa'),
		('+0000','Liberia','','Monrovia','Africa/Monrovia','Africa'),
		('+0300','Kenya','','Nairobi','Africa/Nairobi','Africa'),
		('+0100','Chad','','Ndjamena','Africa/Ndjamena','Africa'),
		('+0100','Niger','','Niamey','Africa/Niamey','Africa'),
		('+0000','Mauritania','','Nouakchott','Africa/Nouakchott','Africa'),
		('+0000','Burkina Faso','','Ouagadougou','Africa/Ouagadougou','Africa'),
		('+0100','Benin','','Porto-Novo','Africa/Porto-Novo','Africa'),
		('+0000','Sao Tome and Principe','','Sao Tome','Africa/Sao_Tome','Africa'),
		('+0000','Mali','','Timbuktu','Africa/Timbuktu','Africa'),
		('+0200','Libya','','Tripoli','Africa/Tripoli','Africa'),
		('+0100','Tunisia','','Tunis','Africa/Tunis','Africa'),
		('+0100','Namibia','','Windhoek','Africa/Windhoek','Africa'),
		('-0900','United States','Alaska','Adak','America/Adak','America'),
		('-0800','United States','Alaska','Anchorage','America/Anchorage','America'),
		('-0400','Anguilla','','The Valley','America/Anguilla','America'),
		('-0400','Antigua and Barbuda','','Antigua','America/Antigua','America'),
		('-0300','Brazil','','Araguaina','America/Araguaina','America'),
		('-0300','Argentina','','Buenos Aires','America/Argentina/Buenos_Aires','America'),
		('-0300','Argentina','','Catamarca','America/Argentina/Catamarca','America'),
		('-0300','Argentina','','Comodoro Rivadavia','America/Argentina/ComodRivadavia','America'),
		('-0300','Argentina','','Cordoba','America/Argentina/Cordoba','America'),
		('-0300','Argentina','','Jujuy','America/Argentina/Jujuy','America'),
		('-0300','Argentina','','La Rioja','America/Argentina/La_Rioja','America'),
		('-0300','Argentina','','Mendoza','America/Argentina/Mendoza','America'),
		('-0300','Argentina','','Rio Gallegos','America/Argentina/Rio_Gallegos','America'),
		('-0300','Argentina','','Salta','America/Argentina/Salta','America'),
		('-0300','Argentina','','San Juan','America/Argentina/San_Juan','America'),
		('-0300','Argentina','','San Luis','America/Argentina/San_Luis','America'),
		('-0300','Argentina','','Tucuman','America/Argentina/Tucuman','America'),
		('-0300','Argentina','','Ushuaia','America/Argentina/Ushuaia','America'),
		('-0400','Aruba','','Oranjestad','America/Aruba','America'),
		('-0400','Paraguay','','Asuncion','America/Asuncion','America'),
		('-0500','Canada','','Atikokan','America/Atikokan','America'),
		('-0900','United States','Alaska','Atka','America/Atka','America'),
		('-0300','Brazil','','Bahia','America/Bahia','America'),
		('-0500','Mexico','','Bahia Banderas','America/Bahia_Banderas','America'),
		('-0400','Barbados','','Bridgetown','America/Barbados','America'),
		('-0300','Brazil','','Belem','America/Belem','America'),
		('-0600','Belize','','Belmopan','America/Belize','America'),
		('-0400','Canada','','Blanc-Sablon','America/Blanc-Sablon','America'),
		('-0400','Brazil','','Boa Vista','America/Boa_Vista','America'),
		('-0500','Colombia','','Bogota','America/Bogota','America'),
		('-0600','United States','Idaho','Boise','America/Boise','America'),
		('-0300','Argentina','','Buenos Aires','America/Buenos_Aires','America'),
		('-0600','Canada','','Cambridge Bay','America/Cambridge_Bay','America'),
		('-0400','Brazil','','Campo Grande','America/Campo_Grande','America'),
		('-0500','Mexico','','Cancun','America/Cancun','America'),
		('-0430','Venezuela','','Caracas','America/Caracas','America'),
		('-0300','Argentina','','Catamarca','America/Catamarca','America'),
		('-0300','French Guiana','','Cayenne','America/Cayenne','America'),
		('-0500','Cayman Islands','','George Town','America/Cayman','America'),
		('-0500','United States','Illinois','Chicago','America/Chicago','America'),
		('-0600','Mexico','','Chihuahua','America/Chihuahua','America'),
		('-0500','Canada','','Coral Harbour','America/Coral_Harbour','America'),
		('-0300','Argentina','','Cordoba','America/Cordoba','America'),
		('-0600','Costa Rica','','San Jose','America/Costa_Rica','America'),
		('-0400','Brazil','','Cuiaba','America/Cuiaba','America'),
		('-0400','Curacao','','Willemstad','America/Curacao','America'),
		('+0000','Greenland','','Danmarkshavn','America/Danmarkshavn','America'),
		('-0700','Canada','','Dawson','America/Dawson','America'),
		('-0700','Canada','','Dawson Creek','America/Dawson_Creek','America'),
		('-0600','United States','Denver','Denver City','America/Denver','America'),
		('-0400','United States','Michigan','Detroit','America/Detroit','America'),
		('-0400','Dominica','','Roseau','America/Dominica','America'),
		('-0600','Canada','','Edmonton','America/Edmonton','America'),
		('-0400','Brazil','','Eirunepe','America/Eirunepe','America'),
		('-0600','El Salvador','','San Salvador','America/El_Salvador','America'),
		('-0700','Mexico','','Ensenada','America/Ensenada','America'),
		('-0400','United States','Indiana','Fort Wayne','America/Fort_Wayne','America'),
		('-0300','Brazil','','Fortaleza','America/Fortaleza','America'),
		('-0300','Canada','','Glace Bay','America/Glace_Bay','America'),
		('-0200','Greenland','','Godthab','America/Godthab','America'),
		('-0300','Canada','','Goose Bay','America/Goose_Bay','America'),
		('-0400','Grand Turk','','Cockburn Town','America/Grand_Turk','America'),
		('-0400','Grenada','','St. George\'s','America/Grenada','America'),
		('-0400','Guadeloupe','','Basse-Terre','America/Guadeloupe','America'),
		('-0600','Guatemala','','Guatemala City','America/Guatemala','America'),
		('-0500','Ecuador','','Guayaquil','America/Guayaquil','America'),
		('-0400','Guyana','','Georgetown','America/Guyana','America'),
		('-0300','Canada','','Halifax','America/Halifax','America'),
		('-0400','Cuba','','Havana','America/Havana','America'),
		('-0700','Mexico','','Hermosillo','America/Hermosillo','America'),
		('-0400','United States','Indiana','Indianapolis','America/Indiana/Indianapolis','America'),
		('-0500','United States','Indiana','Knox','America/Indiana/Knox','America'),
		('-0400','United States','Indiana','Marengo','America/Indiana/Marengo','America'),
		('-0400','United States','Indiana','Petersburg','America/Indiana/Petersburg','America'),
		('-0500','United States','Indiana','Tell City','America/Indiana/Tell_City','America'),
		('-0400','United States','Indiana','Vevay','America/Indiana/Vevay','America'),
		('-0400','United States','Indiana','Vincennes','America/Indiana/Vincennes','America'),
		('-0400','United States','Indiana','Winamac','America/Indiana/Winamac','America'),
		('-0400','United States','Indiana','Indianapolis','America/Indianapolis','America'),
		('-0600','Canada','','Inuvik','America/Inuvik','America'),
		('-0400','Canada','','Iqaluit','America/Iqaluit','America'),
		('-0500','Jamaica','','Kingston','America/Jamaica','America'),
		('-0300','Argentina','','Jujuy','America/Jujuy','America'),
		('-0800','United States','Alaska','Juneau','America/Juneau','America'),
		('-0400','United States','Kentucky','Louisville','America/Kentucky/Louisville','America'),
		('-0400','United States','Kentucky','Monticello','America/Kentucky/Monticello','America'),
		('-0500','United States','Indiana','Knox','America/Knox_IN','America'),
		('-0400','Bolivia','','La Paz','America/La_Paz','America'),
		('-0500','Peru','','Lima','America/Lima','America'),
		('-0700','United States','California','Los Angeles','America/Los_Angeles','America'),
		('-0400','United States','Kentucky','Louisville','America/Louisville','America'),
		('-0300','Brazil','','Maceio','America/Maceio','America'),
		('-0600','Nicaragua','','Managua','America/Managua','America'),
		('-0400','Brazil','','Manaus','America/Manaus','America'),
		('-0400','Saint Martin','','Marigot','America/Marigot','America'),
		('-0400','France','','Martinique','America/Martinique','America'),
		('-0500','Mexico','','Matamoros','America/Matamoros','America'),
		('-0600','Mexico','','Mazatlan','America/Mazatlan','America'),
		('-0300','Argentina','','Mendoza','America/Mendoza','America'),
		('-0500','United States','Michigan','Menominee','America/Menominee','America'),
		('-0500','Mexico','','Merida','America/Merida','America'),
		('-0500','Mexico','','Mexico City','America/Mexico_City','America'),
		('-0200','Saint Pierre and Miquelon','','Saint Pierre','America/Miquelon','America'),
		('-0300','Canada','','Moncton','America/Moncton','America'),
		('-0500','Mexico','','Monterrey','America/Monterrey','America'),
		('-0300','Uruguay','','Montevideo','America/Montevideo','America'),
		('-0400','Canada','','Montreal','America/Montreal','America'),
		('-0400','Montserrat','','Plymouth','America/Montserrat','America'),
		('-0400','Bahamas','','Nassau','America/Nassau','America'),
		('-0400','United States','New York','New York City','America/New_York','America'),
		('-0400','Canada','','Nipigon','America/Nipigon','America'),
		('-0800','United States','Alaska','Nome','America/Nome','America'),
		('-0200','Brazil','','Noronha','America/Noronha','America'),
		('-0500','United States','North Dakota','Center','America/North_Dakota/Center','America'),
		('-0500','United States','North Dakota','New Salem','America/North_Dakota/New_Salem','America'),
		('-0600','Mexico','','Ojinaga','America/Ojinaga','America'),
		('-0500','Panama','','Panama City','America/Panama','America'),
		('-0400','Canada','','Pangnirtung','America/Pangnirtung','America'),
		('-0300','Suriname','','Paramaribo','America/Paramaribo','America'),
		('-0700','United States','Arizona','Phoenix','America/Phoenix','America'),
		('-0500','Haiti','','Port au Prince','America/Port-au-Prince','America'),
		('-0400','Trinidad and Tobago','','Port of Spain','America/Port_of_Spain','America'),
		('-0400','Brazil','','Porto Acre','America/Porto_Acre','America'),
		('-0400','Brazil','','Porto Velho','America/Porto_Velho','America'),
		('-0400','Puerto Rico','','San Juan','America/Puerto_Rico','America'),
		('-0500','United States','Minnesota','Rainy River','America/Rainy_River','America'),
		('-0500','Canada','','Rankin Inlet','America/Rankin_Inlet','America'),
		('-0300','Brazil','','Recife','America/Recife','America'),
		('-0600','Canada','','Regina','America/Regina','America'),
		('-0500','Canada','','Resolute','America/Resolute','America'),
		('-0400','Brazil','','Rio Branco','America/Rio_Branco','America'),
		('-0300','Argentina','','Rosario','America/Rosario','America'),
		('-0700','Argentina','','Santa Isabel','America/Santa_Isabel','America'),
		('-0300','Brazil','','Santarem','America/Santarem','America'),
		('-0400','Chile','','Santiago','America/Santiago','America'),
		('-0400','Dominican Republic','','Santo Domingo','America/Santo_Domingo','America'),
		('-0300','Brazil','','Sao Paulo','America/Sao_Paulo','America'),
		('+0000','Greenland','','Scoresbysund','America/Scoresbysund','America'),
		('-0600','United States','New Mexico','Shiprock','America/Shiprock','America'),
		('-0400','Saint Barthelemy','','Gustavia','America/St_Barthelemy','America'),
		('-0230','Canada','','Saint John\'s','America/St_Johns','America'),
		('-0400','Saint Kitts & Nevis','','Basseterre','America/St_Kitts','America'),
		('-0400','Saint Lucia','','Castries','America/St_Lucia','America'),
		('-0400','United States','Virgin Islands','Saint Thomas','America/St_Thomas','America'),
		('-0400','Saint Vincent and the Grenadines','','Kingstown','America/St_Vincent','America'),
		('-0600','Canada','','Swift Current','America/Swift_Current','America'),
		('-0600','Honduras','','Tegucigalpa','America/Tegucigalpa','America'),
		('-0300','Greenland','','Thule','America/Thule','America'),
		('-0400','Canada','','Thunder Bay','America/Thunder_Bay','America'),
		('-0700','Mexico','','Tijuana','America/Tijuana','America'),
		('-0400','Canada','','Toronto','America/Toronto','America'),
		('-0400','Canada','','Tortola','America/Tortola','America'),
		('-0700','Canada','','Vancouver','America/Vancouver','America'),
		('-0400','United States','Virgin Islands','Virgin','America/Virgin','America'),
		('-0700','Canada','','Whitehorse','America/Whitehorse','America'),
		('-0500','Canada','','Winnipeg','America/Winnipeg','America'),
		('-0800','United States','Alaska','Yakutat','America/Yakutat','America'),
		('-0600','Canada','','Yellowknife','America/Yellowknife','America'),
		('+0800','Antarctica','','Casey','Antarctica/Casey','Antarctica'),
		('+0700','Antarctica','','Davis','Antarctica/Davis','Antarctica'),
		('+1000','Antarctica','','Dumont d\'Urville','Antarctica/DumontDUrville','Antarctica'),
		('+1100','Antarctica','','Macquarie','Antarctica/Macquarie','Antarctica'),
		('+0500','Antarctica','','Mawson','Antarctica/Mawson','Antarctica'),
		('+1200','Antarctica','','McMurdo','Antarctica/McMurdo','Antarctica'),
		('-0400','Antarctica','','Palmer','Antarctica/Palmer','Antarctica'),
		('-0300','Antarctica','','Rothera','Antarctica/Rothera','Antarctica'),
		('+1200','Antarctica','','South Pole','Antarctica/South_Pole','Antarctica'),
		('+0300','Antarctica','','Syowa','Antarctica/Syowa','Antarctica'),
		('+0600','Antarctica','','Vostok','Antarctica/Vostok','Antarctica'),
		('+0200','Svalbard and Jan Mayen','','Longyearbyen','Arctic/Longyearbyen','Arctic'),
		('+0300','Yemen','','Aden','Asia/Aden','Asia'),
		('+0600','Kazakhstan','','Almaty','Asia/Almaty','Asia'),
		('+0300','Jordan','','Amman','Asia/Amman','Asia'),
		('+1200','Russia','','Anadyr','Asia/Anadyr','Asia'),
		('+0500','Kazakhstan','','Aqtau','Asia/Aqtau','Asia'),
		('+0500','Kazakhstan','','Aqtobe','Asia/Aqtobe','Asia'),
		('+0500','Turkmenistan','','Ashgabat','Asia/Ashgabat','Asia'),
		('+0500','Turkmenistan','','Ashkhabad','Asia/Ashkhabad','Asia'),
		('+0300','Iraq','','Baghdad','Asia/Baghdad','Asia'),
		('+0300','Bahrain','','Manama','Asia/Bahrain','Asia'),
		('+0500','Azerbaijan','','Baku','Asia/Baku','Asia'),
		('+0700','Thailand','','Bangkok','Asia/Bangkok','Asia'),
		('+0300','Lebanon','','Beirut','Asia/Beirut','Asia'),
		('+0600','Kyrgyzstan','','Bishkek','Asia/Bishkek','Asia'),
		('+0800','Brunei','','Bandar Seri Begawan','Asia/Brunei','Asia'),
		('+0800','Mongolia','','Choibalsan','Asia/Choibalsan','Asia'),
		('+0800','China','','Chongqing','Asia/Chongqing','Asia'),
		('+0800','China','','Chungking','Asia/Chungking','Asia'),
		('+0530','Sri Lanka','','Colombo','Asia/Colombo','Asia'),
		('+0600','Bangladesh','','Dacca','Asia/Dacca','Asia'),
		('+0300','Syria','','Damascus','Asia/Damascus','Asia'),
		('+0600','Bangladesh','','Dhaka','Asia/Dhaka','Asia'),
		('+0900','East Timor','','Dili','Asia/Dili','Asia'),
		('+0400','United Arab Emirates','','Dubai','Asia/Dubai','Asia'),
		('+0500','Tajikistan','','Dushanbe','Asia/Dushanbe','Asia'),
		('+0300','Palestine','','Gaza','Asia/Gaza','Asia'),
		('+0800','China','','Harbin','Asia/Harbin','Asia'),
		('+0700','Vietnam','','Ho Chi Minh','Asia/Ho_Chi_Minh','Asia'),
		('+0800','China','','Hong Kong','Asia/Hong_Kong','Asia'),
		('+0700','Mongolia','','Hovd','Asia/Hovd','Asia'),
		('+0900','Russia','','Irkutsk','Asia/Irkutsk','Asia'),
		('+0700','Indonesia','','Jakarta','Asia/Jakarta','Asia'),
		('+0900','Indonesia','','Jayapura','Asia/Jayapura','Asia'),
		('+0300','Israel','','Jerusalem','Asia/Jerusalem','Asia'),
		('+0430','Afghanistan','','Kabul','Asia/Kabul','Asia'),
		('+1200','Russia','','Kamchatka','Asia/Kamchatka','Asia'),
		('+0500','Pakistan','','Karachi','Asia/Karachi','Asia'),
		('+0800','China','','Kashgar','Asia/Kashgar','Asia'),
		('+0545','Nepal','','Kathmandu','Asia/Kathmandu','Asia'),
		('+0530','India','','Kolkata','Asia/Kolkata','Asia'),
		('+0800','Russia','','Krasnoyarsk','Asia/Krasnoyarsk','Asia'),
		('+0800','Malaysia','','Kuala Lumpur','Asia/Kuala_Lumpur','Asia'),
		('+0800','Malaysia','','Kuching','Asia/Kuching','Asia'),
		('+0300','Kuwait','','Kuwait City','Asia/Kuwait','Asia'),
		('+0800','China','','Macau','Asia/Macau','Asia'),
		('+1200','Russia','','Magadan','Asia/Magadan','Asia'),
		('+0800','Indonesia','','Makassar','Asia/Makassar','Asia'),
		('+0800','Republic of the Philippines','','Manila','Asia/Manila','Asia'),
		('+0400','Oman','','Muscat','Asia/Muscat','Asia'),
		('+0300','Cyprus','','Nicosia','Asia/Nicosia','Asia'),
		('+0700','Russia','','Novokuznetsk','Asia/Novokuznetsk','Asia'),
		('+0700','Russia','','Novosibirsk','Asia/Novosibirsk','Asia'),
		('+0700','Russia','','Omsk','Asia/Omsk','Asia'),
		('+0500','Kazakhstan','','Oral','Asia/Oral','Asia'),
		('+0700','Cambodia','','Phnom Penh','Asia/Phnom_Penh','Asia'),
		('+0700','Indonesia','','Pontianak','Asia/Pontianak','Asia'),
		('+0900','North Korea','','Pyongyang','Asia/Pyongyang','Asia'),
		('+0300','Qatar','','Doha','Asia/Qatar','Asia'),
		('+0600','Kazakhstan','','Qyzylorda','Asia/Qyzylorda','Asia'),
		('+0630','Myanmar','','Rangoon','Asia/Rangoon','Asia'),
		('+0300','Saudi Arabia','','Riyadh','Asia/Riyadh','Asia'),
		('+0700','Vietnam','','Saigon','Asia/Saigon','Asia'),
		('+1100','Russia','','Sakhalin','Asia/Sakhalin','Asia'),
		('+0500','Uzbekistan','','Samarkand','Asia/Samarkand','Asia'),
		('+0900','South Korea','','Seoul','Asia/Seoul','Asia'),
		('+0800','China','','Shanghai','Asia/Shanghai','Asia'),
		('+0800','Republic of Singapore','','Singapore','Asia/Singapore','Asia'),
		('+0800','Taiwan','','Taipei','Asia/Taipei','Asia'),
		('+0500','Uzbekistan','','Tashkent','Asia/Tashkent','Asia'),
		('+0400','Georgia','','Tbilisi','Asia/Tbilisi','Asia'),
		('+0430','Iran','','Tehran','Asia/Tehran','Asia'),
		('+0300','Israel','','Tel Aviv','Asia/Tel_Aviv','Asia'),
		('+0600','Bhutan','','Thimphu','Asia/Thimphu','Asia'),
		('+0900','Japan','','Tokyo','Asia/Tokyo','Asia'),
		('+0800','Mongolia','','Ulaanbaatar','Asia/Ulaanbaatar','Asia'),
		('+0800','China','','Urumqi','Asia/Urumqi','Asia'),
		('+0700','Laos','','Vientiane','Asia/Vientiane','Asia'),
		('+1100','Russia','','Vladivostok','Asia/Vladivostok','Asia'),
		('+1000','Russia','','Yakutsk','Asia/Yakutsk','Asia'),
		('+0600','Russia','','Yekaterinburg','Asia/Yekaterinburg','Asia'),
		('+0500','Armenia','','Yerevan','Asia/Yerevan','Asia'),
		('+0000','Portugal','','Azores','Atlantic/Azores','Atlantic'),
		('-0300','Bermuda','','Bermuda','Atlantic/Bermuda','Atlantic'),
		('+0100','Spain','','Canary','Atlantic/Canary','Atlantic'),
		('-0100','Cape Verde','','Cape Verde','Atlantic/Cape_Verde','Atlantic'),
		('+0100','Faroe Islands','','Faroe','Atlantic/Faroe','Atlantic'),
		('+0100','Portugal','','Madeira','Atlantic/Madeira','Atlantic'),
		('+0000','Iceland','','Reykjavik','Atlantic/Reykjavik','Atlantic'),
		('-0200','South Georgia and the South Sandwich Islands','','South Georgia','Atlantic/South_Georgia','Atlantic'),
		('+0000','Saint Helena','','Saint Helena','Atlantic/St_Helena','Atlantic'),
		('-0400','Falkland Islands','','Stanley','Atlantic/Stanley','Atlantic'),
		('+1000','Australia','','ACT','Australia/ACT','Australia'),
		('+0930','Australia','','Adelaide','Australia/Adelaide','Australia'),
		('+1000','Australia','','Brisbane','Australia/Brisbane','Australia'),
		('+0930','Australia','','Broken Hill','Australia/Broken_Hill','Australia'),
		('+1000','Australia','','Canberra','Australia/Canberra','Australia'),
		('+1000','Australia','','Currie','Australia/Currie','Australia'),
		('+0930','Australia','','Darwin','Australia/Darwin','Australia'),
		('+0845','Australia','','Eucla','Australia/Eucla','Australia'),
		('+1000','Australia','','Hobart','Australia/Hobart','Australia'),
		('+1030','Australia','','LHI','Australia/LHI','Australia'),
		('+1000','Australia','','Lindeman','Australia/Lindeman','Australia'),
		('+1030','Australia','','Lord Howe','Australia/Lord_Howe','Australia'),
		('+1000','Australia','','Melbourne','Australia/Melbourne','Australia'),
		('+0930','Australia','','North','Australia/North','Australia'),
		('+1000','Australia','','NSW','Australia/NSW','Australia'),
		('+0800','Australia','','Perth','Australia/Perth','Australia'),
		('+1000','Australia','','Queensland','Australia/Queensland','Australia'),
		('+0930','Australia','','South','Australia/South','Australia'),
		('+1000','Australia','','Sydney','Australia/Sydney','Australia'),
		('+1000','Australia','','Tasmania','Australia/Tasmania','Australia'),
		('+1000','Australia','','Victoria','Australia/Victoria','Australia'),
		('+0800','Australia','','West','Australia/West','Australia'),
		('+0930','Australia','','Yancowinna','Australia/Yancowinna','Australia'),
		('+0200','Netherlands','','Amsterdam','Europe/Amsterdam','Europe'),
		('+0200','Andorra','','Andorra la Vella','Europe/Andorra','Europe'),
		('+0300','Greece','','Athens','Europe/Athens','Europe'),
		('+0100','Great Britain','','Belfast','Europe/Belfast','Europe'),
		('+0200','Serbia','','Belgrade','Europe/Belgrade','Europe'),
		('+0200','Germany','','Berlin','Europe/Berlin','Europe'),
		('+0200','Slovakia','','Bratislava','Europe/Bratislava','Europe'),
		('+0200','Belgium','','Brussels','Europe/Brussels','Europe'),
		('+0300','Romania','','Bucharest','Europe/Bucharest','Europe'),
		('+0200','Hungary','','Budapest','Europe/Budapest','Europe'),
		('+0300','Moldova','','Chisinau','Europe/Chisinau','Europe'),
		('+0200','Denmark','','Copenhagen','Europe/Copenhagen','Europe'),
		('+0100','Ireland','','Dublin','Europe/Dublin','Europe'),
		('+0200','Gibraltar','','Gibraltar','Europe/Gibraltar','Europe'),
		('+0100','Guernsey','','Guernsey','Europe/Guernsey','Europe'),
		('+0300','Finland','','Helsinki','Europe/Helsinki','Europe'),
		('+0100','Isle of Man','','Isle of Man','Europe/Isle_of_Man','Europe'),
		('+0300','Turkey','','Istanbul','Europe/Istanbul','Europe'),
		('+0100','Jersey','','Jersey','Europe/Jersey','Europe'),
		('+0300','Russia','','Kaliningrad','Europe/Kaliningrad','Europe'),
		('+0300','Ukraine','','Kiev','Europe/Kiev','Europe'),
		('+0100','Portugal','','Lisbon','Europe/Lisbon','Europe'),
		('+0200','Slovenia','','Ljubljana','Europe/Ljubljana','Europe'),
		('+0100','Great Britain','','London','Europe/London','Europe'),
		('+0200','Luxembourg','','Luxembourg','Europe/Luxembourg','Europe'),
		('+0200','Spain','','Madrid','Europe/Madrid','Europe'),
		('+0200','Malta','','Malta','Europe/Malta','Europe'),
		('+0300','Aaland Islands','','Mariehamn','Europe/Mariehamn','Europe'),
		('+0300','Belarus','','Minsk','Europe/Minsk','Europe'),
		('+0200','Monaco','','Monaco','Europe/Monaco','Europe'),
		('+0400','Russia','','Moscow','Europe/Moscow','Europe'),
		('+0300','Cyprus','','Nicosia','Europe/Nicosia','Europe'),
		('+0200','Norway','','Oslo','Europe/Oslo','Europe'),
		('+0200','France','','Paris','Europe/Paris','Europe'),
		('+0200','Montenegro','','Podgorica','Europe/Podgorica','Europe'),
		('+0200','Czech Republic','','Prague','Europe/Prague','Europe'),
		('+0300','Latvia','','Riga','Europe/Riga','Europe'),
		('+0200','Italy','','Rome','Europe/Rome','Europe'),
		('+0400','Russia','','Samara','Europe/Samara','Europe'),
		('+0200','San Marino','','San Marino','Europe/San_Marino','Europe'),
		('+0200','Bosnia and Herzegovina','','Sarajevo','Europe/Sarajevo','Europe'),
		('+0300','Ukraine','','Simferopol','Europe/Simferopol','Europe'),
		('+0200','Macedonia','','Skopje','Europe/Skopje','Europe'),
		('+0300','Bulgaria','','Sofia','Europe/Sofia','Europe'),
		('+0200','Sweden','','Stockholm','Europe/Stockholm','Europe'),
		('+0300','Estonia','','Tallinn','Europe/Tallinn','Europe'),
		('+0200','Albania','','Tirane','Europe/Tirane','Europe'),
		('+0300','Moldova','','Tiraspol','Europe/Tiraspol','Europe'),
		('+0300','Ukraine','','Uzhgorod','Europe/Uzhgorod','Europe'),
		('+0200','Liechtenstein','','Vaduz','Europe/Vaduz','Europe'),
		('+0200','Vatican','','Vatican City','Europe/Vatican','Europe'),
		('+0200','Austria','','Vienna','Europe/Vienna','Europe'),
		('+0300','Lithuania','','Vilnius','Europe/Vilnius','Europe'),
		('+0400','Russia','','Volgograd','Europe/Volgograd','Europe'),
		('+0200','Poland','','Warsaw','Europe/Warsaw','Europe'),
		('+0200','Croatia','','Zagreb','Europe/Zagreb','Europe'),
		('+0300','Ukraine','','Zaporozhye','Europe/Zaporozhye','Europe'),
		('+0200','Switzerland','','Zurich','Europe/Zurich','Europe'),
		('+0300','Madagascar','','Antananarivo','Indian/Antananarivo','Indian'),
		('+0600','British Indian Ocean Territory','','Chagos','Indian/Chagos','Indian'),
		('+0700','Christmas Island','','Christmas','Indian/Christmas','Indian'),
		('+0630','Cocos Islands','','Cocos','Indian/Cocos','Indian'),
		('+0300','Comoros','','Comoro','Indian/Comoro','Indian'),
		('+0500','French Southern and Antarctic Lands','','Kerguelen','Indian/Kerguelen','Indian'),
		('+0400','Seychelles','','Mahe','Indian/Mahe','Indian'),
		('+0500','Maldives','','Maldives','Indian/Maldives','Indian'),
		('+0400','Mauritius','','Mauritius','Indian/Mauritius','Indian'),
		('+0300','Mayotte','','Mayotte','Indian/Mayotte','Indian'),
		('+0400','Reunion','','Reunion','Indian/Reunion','Indian'),
		('-1100','Samoa','','Apia','Pacific/Apia','Pacific'),
		('+1200','New Zealand','','Auckland','Pacific/Auckland','Pacific'),
		('+1245','New Zealand','','Chatham','Pacific/Chatham','Pacific'),
		('+1000','Micronesia','','Chuuk','Pacific/Chuuk','Pacific'),
		('-0600','Chile','','Easter','Pacific/Easter','Pacific'),
		('+1100','Vanuatu','','Efate','Pacific/Efate','Pacific'),
		('+1300','Kiribati','','Enderbury','Pacific/Enderbury','Pacific'),
		('-1000','Tokelau','','Fakaofo','Pacific/Fakaofo','Pacific'),
		('+1200','Fiji','','Fiji','Pacific/Fiji','Pacific'),
		('+1200','Tuvalu','','Funafuti','Pacific/Funafuti','Pacific'),
		('-0600','Ecuador','','Galapagos','Pacific/Galapagos','Pacific'),
		('-0900','French Polynesia','','Gambier','Pacific/Gambier','Pacific'),
		('+1100','Solomon Islands','','Guadalcanal','Pacific/Guadalcanal','Pacific'),
		('+1000','Guam','','Guam','Pacific/Guam','Pacific'),
		('-1000','United States','','Honolulu','Pacific/Honolulu','Pacific'),
		('-1000','United States','','Johnston','Pacific/Johnston','Pacific'),
		('+1400','Kiribati','','Kiritimati','Pacific/Kiritimati','Pacific'),
		('+1100','Micronesia','','Kosrae','Pacific/Kosrae','Pacific'),
		('+1200','Marshall Islands','','Kwajalein','Pacific/Kwajalein','Pacific'),
		('+1200','Marshall Islands','','Majuro','Pacific/Majuro','Pacific'),
		('-0930','French Polynesia','','Marquesas','Pacific/Marquesas','Pacific'),
		('-1100','United States','','Midway','Pacific/Midway','Pacific'),
		('+1200','Nauru','','Nauru','Pacific/Nauru','Pacific'),
		('-1100','Niue','','Niue','Pacific/Niue','Pacific'),
		('+1130','Norfolk Island','','Norfolk','Pacific/Norfolk','Pacific'),
		('+1100','New Caledonia','','Noumea','Pacific/Noumea','Pacific'),
		('-1100','Samoa','','Pago Pago','Pacific/Pago_Pago','Pacific'),
		('+0900','Palau','','Palau','Pacific/Palau','Pacific'),
		('-0800','Pitcairn','','Pitcairn','Pacific/Pitcairn','Pacific'),
		('+1100','Micronesia','','Pohnpei','Pacific/Pohnpei','Pacific'),
		('+1100','Micronesia','','Ponape','Pacific/Ponape','Pacific'),
		('+1000','Papua New Guinea','','Port_Moresby','Pacific/Port_Moresby','Pacific'),
		('-1000','Cook Islands','','Rarotonga','Pacific/Rarotonga','Pacific'),
		('+1000','Northern Mariana Islands','','Saipan','Pacific/Saipan','Pacific'),
		('-1100','Samoa','','Samoa','Pacific/Samoa','Pacific'),
		('-1000','French Polynesia','','Tahiti','Pacific/Tahiti','Pacific'),
		('+1200','Kiribati','','Tarawa','Pacific/Tarawa','Pacific'),
		('+1300','Tonga','','Tongatapu','Pacific/Tongatapu','Pacific'),
		('+1000','Micronesia','','Truk','Pacific/Truk','Pacific'),
		('+1200','United States','','Wake','Pacific/Wake','Pacific'),
		('+1200','Wallis and Futuna','','Wallis','Pacific/Wallis','Pacific'),
		('+1000','Micronesia','','Yap','Pacific/Yap','Pacific');
